parameters:
    zorbus_faq.faq.admin.class: Zorbus\FaqBundle\Admin\FaqAdmin
    zorbus_faq.item.admin.class: Zorbus\FaqBundle\Admin\ItemAdmin

    zorbus_faq.faq.entity.class: Zorbus\FaqBundle\Entity\Faq
    zorbus_faq.item.entity.class: Zorbus\FaqBundle\Entity\Item

    zorbus_faq.faq.controller.class: SonataAdminBundle:CRUD
    zorbus_faq.item.controller.class: SonataAdminBundle:CRUD

    zorbus_block.service.faq.class: Zorbus\FaqBundle\Model\BlockFaqConfig

services:
    zorbus_faq.faq.admin:
        class: %zorbus_faq.faq.admin.class%
        arguments: [~, %zorbus_faq.faq.entity.class%, %zorbus_faq.faq.controller.class%]
        calls:
            - [setTranslationDomain, [FaqBundle]]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Faqs, label: Faqs }
    zorbus_faq.item.admin:
        class: %zorbus_faq.item.admin.class%
        arguments: [~, %zorbus_faq.item.entity.class%, %zorbus_faq.item.controller.class%]
        calls:
            - [setTranslationDomain, [FaqBundle]]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Faqs, label: Items }
    zorbus_faq.block.faq:
        class: %zorbus_block.service.faq.class%
        scope: prototype
        arguments: ['@zorbus_block.block.admin', '@form.factory', '@http_kernel']
        tags:
            - { name: zorbus_block.block, category: FAQs }
