<?php

namespace Zorbus\FaqBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FaqRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaqRepository extends EntityRepository
{
}
